---
- name: "Step 1: Generate SSL/TLS Certificates"
  hosts: all
  become: yes
  
  vars:
    # Certificate variables
    base_directory: "/opt/network-sensors"
    cert_directory: "{{ base_directory }}/certificates"
    cert_validity_days: 365
    cert_country: "US"
    cert_state: "State"
    cert_locality: "City"
    cert_organization: "NetworkSensors"
    server_hostname: "sensor-node-01"
    server_domain: "local"
  
  tasks:
    - name: Display certificate generation phase
      debug:
        msg:
          - "=========================================="
          - "PHASE 1: CERTIFICATE GENERATION"
          - "=========================================="
          - "Generating self-signed certificates for:"
          - "  - Elasticsearch (HTTPS)"
          - "  - Kibana (HTTPS)"
          - "  - Fleet Server (HTTPS)"
          - "Validity: {{ cert_validity_days }} days"
          - "Including sensor IP: {{ ansible_host }}"
          - "=========================================="
      tags: ['always']

    - name: Include certificates role
      import_role:
        name: certificates
      tags: ['certs']

    - name: Display certificate locations
      debug:
        msg:
          - "=========================================="
          - "PHASE 1: COMPLETED"
          - "=========================================="
          - "Certificates stored in: {{ cert_directory }}"
          - "Files created:"
          - "  - ca.crt (Certificate Authority)"
          - "  - elasticsearch.crt + elasticsearch-key.pem"
          - "  - kibana.crt + kibana-key.pem"
          - "  - fleet-server.crt + fleet-server-key.pem"
          - ""
          - "All certificates include SAN entries for:"
          - "  - DNS: {{ server_hostname }}, {{ server_hostname }}.{{ server_domain }}, localhost"
          - "  - IP: 127.0.0.1, {{ ansible_host }}"
          - "=========================================="
      tags: ['always']
